variable "name" {}
variable "hostname" {}
variable "hostname_suffix" {}
variable "master_node_count" {}
variable "packet_facility" {}
variable "packet_project_id" {}
variable "packet_billing_cycle" {}
variable "packet_operating_system" {}
variable "packet_master_device_plan" {}
variable "master_cloud_init" {}
