apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: etcd-server
  name: etcd-server
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - . /etc/srv/kubernetes/etcd.env && /usr/local/bin/etcd 1>>/var/log/etcd.log 2>&1
    env:
    - name: ETCD_NAME
      value: ${ fqdn }
    - name: ETCD_DATA_DIR
      value: /var/etcd/data
    - name: ETCD_DISCOVERY
      value: ${ etcd_discovery }
    image: ${ etcd_registry }:${ etcd_tag }
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 4001
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd-container
    ports:
    - containerPort: 2380
      hostPort: 2380
      name: serverport
    - containerPort: 4001
      hostPort: 4001
      name: clientport
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /var/etcd/data
      name: varetcdata
    - mountPath: /var/log
      name: varlogetcd
    - mountPath: /etc/srv/kubernetes
      name: cloudvars
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/etcd/data
    name: varetcdata
  - hostPath:
      path: /var/log
    name: varlogetcd
  - hostPath:
      path: /etc/srv/kubernetes
    name: cloudvars
status: {}
