variable "ami_id" {}
variable "etcd_security_group_id" {}
variable "external_elb_security_group_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "name" {}
variable "region" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "instance_profile_name" {}
variable "master_node_count" {}
