variable "ami_id" {}
variable "cluster_domain" {}
variable "kubelet_image_url" {}
variable "kubelet_image_tag" {}
variable "depends_id" {}
variable "dns_service_ip" {}
variable "etcd_security_group_id" {}
variable "external_elb_security_group_id" {}
variable "instance_type" {}
variable "internal_tld" {}
variable "key_name" {}
variable "name" {}
variable "pod_cidr" {}
variable "region" {}
variable "service_cidr" {}
variable "subnet_ids_private" {}
variable "subnet_ids_public" {}
variable "vpc_id" {}
variable "ca" {}
variable "k8s_etcd" {}
variable "k8s_etcd_key" {}
variable "k8s_apiserver" {}
variable "k8s_apiserver_key" {}
variable "instance_profile_name" {}
variable "master_node_count" {}
