apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: dns-server
  name: dns-server
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /coredns 
    image: coredns/coredns:011
    livenessProbe:
      tcpSocket:
        port: 53
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: dns-container
    ports:
    - containerPort: 53
      hostPort: 53
      name: dnsport
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - name: config-volume
      mountPath: /etc/coredns
    - mountPath: /etc/srv/kubernetes
      name: cloudvars
  initContainers:
  - command:
    - /bin/sh
    - -c
    - /seed/entrypoint.sh
    image: docker.io/iidlx/bootstrap
    name: seed-dns
    volumeMounts:
    - name: cloudvars
      mountPath: /etc/srv/kubernetes
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/dns
    name: config-volume
  - hostPath:
      path: /etc/srv/kubernetes
    name: cloudvars
status: {}
