apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: dns-server
  name: dns-server
  namespace: kube-system
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "seed-dns",
            "image": "docker.io/iidlx/bootstrap",
            "command": [
              "/bin/sh", "-c", "/seed/entrypoint.sh"
            ],
            "volumeMounts":[{"name":"cloudvars","mountPath":"/etc/srv/kubernetes"}]
          }
        ]'
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /coredns -conf /etc/coredns/Corefile
    image: coredns/coredns:011
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 4001
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: dns-container
    ports:
    - containerPort: 53
      hostPort: 53
      name: dnsport
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - name: config-volume
      mountPath: /etc/coredns
    - mountPath: /etc/srv/kubernetes
      name: cloudvars
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/dns
    name: config-volume
  - hostPath:
      path: /etc/srv/kubernetes
    name: cloudvars
status: {}
