apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: etcd-proxy
  name: etcd-proxy
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd 1>>/var/log/etcd.log 2>&1
    env:
    - name: ETCD_DATA_DIR
      value: /var/etcd/data
    - name: ETCD_DISCOVERY
      value: ${ etcd_discovery }
    - name: ETCD_PROXY
      value: "on"
    image: ${ etcd_image }:${ etcd_tag }
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 4001
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd-proxy
    ports:
    - containerPort: 2379
      hostPort: 2379
      name: serverport
    - containerPort: 4001
      hostPort: 4001
      name: clientport
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: etcssl
      readOnly: true
    - mountPath: /var/etcd/data
      name: varetcdata
    - mountPath: /var/log
      name: varlogetcd
  hostNetwork: true
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: etcssl
  - hostPath:
      path: /var/etcd/data
    name: varetcdata
  - hostPath:
      path: /var/log
    name: varlogetcd
status: {}
