variable "name" {}
variable "location" {}
variable "bastion_vm_size" {}
variable "image_publisher" {}
variable "image_offer"     {}
variable "image_sku"       {}
variable "image_version"   {}
variable "admin_username" {}
variable "subnet_id" {}
variable "availability_id" {}
variable "storage_container" {}
variable "storage_primary_endpoint" {}
variable "data_dir" {}
