variable "name" { default = "test" }
variable "internal_tld" { default = "cncf.demo" }
variable "master_node_count" { default = "3" }
variable "worker_node_count" { default = "3" }
#variable "master_vm_size"   { default = "Standard_A2" }
#variable "worker-vm-size"   { default = "Standard_A2" }
#variable "bastion-vm-size"   { default = "Standard_A2" }
# Set from https://quay.io/repository/coreos/hyperkube?tab=tags
variable "kubelet_image_url" { default = "quay.io/coreos/hyperkube"}
variable "kubelet_image_tag" { default = "v1.4.7_coreos.0"}
#variable "image-publisher" { default = "CoreOS" }
#variable "image-offer"     { default = "CoreOS" }
#variable "image-sku"       { default = "Stable" }
#variable "image-version"   { default = "1298.6.0" }
variable "region"          { default = "us-central1" }
variable "zone"            { default = "us-central1-a" }
variable "project"         { default = "test-163823" }
variable "cluster_domain" { default = "cluster.local" }
# variable "admin_username" { default = "cncf"}
variable "cidr" { default = "10.0.0.0/16" }
variable "pod_cidr" { default = "10.2.0.0/16" }
variable "service_cidr"   { default = "10.3.0.0/24" }
variable "k8s_service_ip" { default = "10.3.0.1" }
variable "dns_service_ip" { default = "10.3.0.10" }
# variable "allow-ssh-cidr" { default = "0.0.0.0/0" }
variable "data_dir" { default = "/cncf/data" }
# variable "name-servers-file" { default = "google_dns_zone"}
variable "domain" { default = "cncf.ci" }
