apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    k8s-app: kube-apiserver
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver --admission-control=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --allow-privileged=true --apiserver-count=${ master_node_count } --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --audit-log-path=/var/log/audit.log --authorization-mode=Node,RBAC --token-auth-file=/etc/srv/kubernetes/known_tokens.csv --bind-address=0.0.0.0 --secure-port=443 --kubelet-preferred-address-types=Hostname --client-ca-file=/etc/srv/kubernetes/pki/ca-certificates.crt --enable-swagger-ui=true --etcd-servers=http://${ etcd_endpoint }:4001 --event-ttl=1h --insecure-bind-address=127.0.0.1 --kubelet-certificate-authority=/etc/srv/kubernetes/pki/ca-certificates.crt --kubelet-client-certificate=/etc/srv/kubernetes/pki/master.crt --kubelet-client-key=/etc/srv/kubernetes/pki/master.key --kubelet-https=true --cloud-provider=${ cloud_provider } ${ cloud_config } --service-account-key-file=/etc/srv/kubernetes/pki/ca-certificates.key --service-cluster-ip-range=${ service_cidr } --tls-cert-file=/etc/srv/kubernetes/pki/master.crt --tls-private-key-file=/etc/srv/kubernetes/pki/master.key --v=2 1>>/var/log/kube-apiserver.log 2>&1
    image: ${ kube_apiserver_image }:${ kube_apiserver_tag }
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    resources:
      requests:
        cpu: 150m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: etcssl
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etcpkitls
      readOnly: true
    - mountPath: /etc/pki/ca-trust
      name: etcpkica-trust
      readOnly: true
    - mountPath: /var/ssl
      name: varssl
      readOnly: true
    - mountPath: /etc/openssl
      name: etcopenssl
      readOnly: true
    - mountPath: /etc/srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /srv/sshproxy
      name: srvsshproxy
      readOnly: true
    - mountPath: /var/log
      name: logfile
  hostNetwork: true
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: etcssl
  - hostPath:
      path: /etc/pki/tls
    name: etcpkitls
  - hostPath:
      path: /etc/pki/ca-trust
    name: etcpkica-trust
  - hostPath:
      path: /var/ssl
    name: varssl
  - hostPath:
      path: /etc/openssl
    name: etcopenssl
  - hostPath:
      path: /etc/srv/kubernetes
    name: srvkube
  - hostPath:
      path: /srv/sshproxy
    name: srvsshproxy
  - hostPath:
      path: /var/log
    name: logfile
status: {}
