variable "ami_id" {}
variable "master_security" {}
variable "external_lb_security" {}
variable "internal_lb_security" {}
variable "instance_type" {}
variable "key_name" {}
variable "name" {}
variable "region" {}
variable "subnet_public_id" {}
variable "subnet_private_id" {}
variable "vpc_id" {}
variable "instance_profile_name" {}
variable "master_node_count" {}
variable "master_cloud_init" {}
