variable "name" {}
variable "worker_node_count" {}
variable "packet_facility" {}
variable "packet_project_id" {}
variable "packet_billing_cycle" {}
variable "packet_operating_system" {}
variable "packet_worker_device_plan" {}
variable "kubelet_image_url" {}
variable "kubelet_image_tag" {}
variable "dns_service_ip" {}
variable "cluster_domain" {}
variable "internal_tld" {}
variable "pod_cidr" {}
variable "service_cidr" {}
variable "ca" {}
variable "k8s_etcd" {}
variable "k8s_etcd_key" {}
variable "k8s_worker" {}
variable "k8s_worker_key" {}
variable "data_dir" {}
variable "etcd_discovery" {}
