variable "count" {}
variable "availability_domain" {}
variable "compartment_id" {}
variable "hostname" {}
variable "hostname_suffix" {}
variable "image_id" {}
variable "shape" {}
variable "subnet_id" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "master_cloud_init" {}
variable "coreos_image_ocid" {}
