variable "name" {}
variable "hostname_suffix" {}
variable "hostname_path" {}
variable "label_prefix" {}
variable "display_name_prefix" {}
variable "hostname_label_prefix" {}
variable "master_cloud_init" {}
variable "count" {}
variable "availability_domain" {}
variable "compartment_id" {}
variable "image_id" {}
variable "shape" {}
variable "subnet_id" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "coreos_image_ocid" {}
