variable "location" {}
variable "subnet_id" {}
variable "name" {}
variable "worker_vm_size" {}
variable "worker_node_count" {}
variable "image_publisher" {}
variable "image_offer"     {}
variable "image_sku"       {}
variable "image_version"   {}
variable "storage_account" {}
variable "storage_primary_endpoint" {}
variable "storage_container" {}
variable "availability_id" {}
variable "external_lb" {}
variable "cluster_domain" {}
variable "dns_service_ip" {}
variable "internal_tld" {}
variable "admin_username" {}
variable "kubelet_image_url" {}
variable "kubelet_image_tag" {}
variable "k8s_cloud_config" {}
variable "ca" {}
variable "k8s_worker" {}
variable "k8s_worker_key" {}
variable "data_dir" {}
