variable "location" {}
variable "subnet_id" {}
variable "name" {}
variable "worker_vm_size" {}
variable "worker_node_count" {}
variable "image_publisher" {}
variable "image_offer"     {}
variable "image_sku"       {}
variable "image_version"   {}
variable "storage_account" {}
variable "storage_primary_endpoint" {}
variable "storage_container" {}
variable "availability_id" {}
variable "external_lb" {}
variable "cluster_domain" {}
variable "dns_service_ip" {}
variable "pod_cidr" {}
variable "non_masquerade_cidr" {}
variable "internal_tld" {}
variable "admin_username" {}
variable "kube_proxy_registry" {}
variable "kube_proxy_tag" {}
variable "ca" {}
variable "worker" {}
variable "worker_key" {}
variable "data_dir" {}
variable "azure_cloud" {}
variable "kube_proxy_token" {}
variable "dns_suffix" {}
variable "internal_lb_ip" {}
