variable "name" {}
variable "region" {}
variable "zone" {}
variable "project" {}
variable "master_vm_size" {}
variable "master_node_count" {}
variable "image_id" {}
variable "internal_lb_ip" {}
variable "network" {}
variable "subnetwork" {}
