variable "name" {}
variable "master_flavor_name" {}
variable "master_image_name" {}
variable "master_node_count" {}
variable "internal_network_id" {}
variable "internal_network_subnet_id" {}
variable "master_cloud_init" {}
variable "internal_lb_http_pool_id" {}
variable "internal_lb_https_pool_id" {}
variable "security_group_name" {}
